### ISSUE TITLE
Reports and Applications doesn't show any data

### ISSUE THREAD

**Issue by leicht-io** [vaibhavpandeyvpz/acraviz#2]
I have created an application and provoked some exceptions in my application.

I have ACRA version 4.8.5 installed and a PHP7 and MySQL 5.5.49 backend.
When checking the tables, reports and applications, i see correctly formatted data but when visiting the corrosponding pages they don't show any data. The HTML is working as expected, but the HTML table is empty.

Can you please help me through this problem? Thank you.

**Comment by leicht-io** [comment]
As a side note; it is possible for me to see data on the dashboard. See the attached screenshots.

**Dashboard:**
![1](https://cloud.githubusercontent.com/assets/3056379/15678120/6655bba4-274d-11e6-963d-256df277cc6e.JPG)

**Applications:**
![2](https://cloud.githubusercontent.com/assets/3056379/15678122/66818f7c-274d-11e6-9462-689a43d63e65.JPG)

**Reports:**
![3](https://cloud.githubusercontent.com/assets/3056379/15678121/665b7698-274d-11e6-94e3-3b189a148936.JPG)

**Comment by ChristianLJ** [comment]
And from my DB called acraviz:
![4](https://cloud.githubusercontent.com/assets/3056379/15678292/1b714e90-274e-11e6-929f-b7ff9bce2506.JPG)
![5](https://cloud.githubusercontent.com/assets/3056379/15678293/1b738e26-274e-11e6-8231-92d28d4c8efa.JPG)

Let me know if you need more information.

**Comment by vaibhavpandeyvpz** [comment]
Can you please take a note from your browser's console. I believe the DataTables aren't being initialized or errored.

**Comment by leicht-io** [comment]
There are no errors in the JS console and no network errors as well.

**Comment by vaibhavpandeyvpz** [comment]
I will install it locally on similar sys config & investigate in a couple hours.

**Comment by leicht-io** [comment]
Thank you - that is nice of you. I will continue to investegate the problem.

**Comment by vaibhavpandeyvpz** [comment]
Unfortunately, I tested it on my machine with `php 7.0.7` and were unable to reproduce same case. Please check the network tab or browser's console while your acraviz pages load to see if the error is at server.

**Comment by leicht-io** [comment]
Both the network and console tabs are empty. See below:
![1](https://cloud.githubusercontent.com/assets/3056379/15707593/c894f472-27f9-11e6-952f-5a2dff49f188.JPG)

![2](https://cloud.githubusercontent.com/assets/3056379/15707594/c895f1a6-27f9-11e6-9e01-a0232afea386.JPG)

For testing purpose i am editing DatatablesController.php and setting a var_dump("hello") on the first line of the public function applications(). When reloading the applications page my browser doesn't print a var_dump of the String hello as i imagine it should. Does this help you?

**Comment by leicht-io** [comment]
The following output is from  the app.log:

`[2016-06-01 13:33:42] myapp.INFO: Matched route "applications". {"route_parameters":{"_controller":"ApplicationsController:index","_route":"applications"},"request_uri":"http://domain.tld/applications"} []
[2016-06-01 13:33:42] myapp.DEBUG: Read existing security token from the session. {"key":"_security_admin"} []
[2016-06-01 13:33:42] myapp.DEBUG: User was reloaded from a user provider. {"username":"christianlj","provider":"Acraviz\\Http\\Security\\UserProvider"} []
[2016-06-01 13:33:42] myapp.INFO: > GET /applications [] []
[2016-06-01 13:33:42] myapp.INFO: < 200 [] []
[2016-06-01 13:33:42] myapp.DEBUG: Stored the security token in the session. {"key":"_security_admin"} []
`

**Comment by vaibhavpandeyvpz** [comment]
Will it be possible if I could share your screen via Teamviewer where you login to the acraviz?

EDIT:
Or you can grant a temporary access to the hosted acraviz accessible via HTTP, if feasible.

**Comment by leicht-io** [comment]
Yes, of couse. I have mailed you some credentials.

**Comment by vaibhavpandeyvpz** [comment]
I got your email, will check those in a fee hours. Just woke up :-P

**Comment by vaibhavpandeyvpz** [comment]
Issue resolved, as assets were not compiled using `gulp` command (which should run automatically when using `composer create-project` as documented).
