### ISSUE TITLE
Cannot delete multiple reports at once

### ISSUE THREAD

**Issue by diantahoc** [vaibhavpandeyvpz/acraviz#3]
I tried to delete more than 1 report at once and it failed by showing a "Select at least 1 report" message.

My gut tell me that the issue reside in the JavaScript code but I didn't take the time to check it, so here I am.

If you need more information let me know. I love your project because I finally found a nice, modern ACRA backend that suits my needs.

![scr](https://cloud.githubusercontent.com/assets/2142305/19008009/fe5131c6-8770-11e6-97db-678ac759b3e1.png)

**Comment by robindijkhof** [comment]
Having the same problem

**Comment by felixble** [comment]
Hey there !

I found the problem and already sent a pull request with the solution ;-)

@vaibhavpandeyvpz this is really a very nice project! It is well structured and very easy to read. Thank you!
